# vpc variables
variable "vpc_cidr" {}
variable "tag-vpc" {}
variable "public_subnet_1_cidr" {}
variable "az_1" {}
variable "tag-Public_subnet_1" {}
variable "public_subnet_2_cidr" {}
variable "az_2" {}
variable "tag-Public_subnet_2" {}
variable "private_subnet_1_cidr" {}
variable "tag-Private_subnet_1" {}
variable "private_subnet_2_cidr" {}
variable "tag-Private_subnet_2" {}
variable "tag-igw" {}
variable "key_name" {}
variable "keypair_path" {}
variable "tag-natgw" {}
variable "RT_cidr" {}
variable "tag-public_RT" {}
variable "tag-private_RT" {}
variable "port_ssh" {}
variable "tag-Bastion-Ansible_SG" {}
variable "port_proxy" {}
variable "port_http" {}
variable "port_https" {}
variable "tag-Docker-SG" {}
variable "tag-Jenkins_SG" {}
variable "port_sonar" {}
variable "tag-Sonarqube_SG" {}
variable "port_proxy_nex" {}
variable "port_proxy_nex_2" {}
variable "tag-Nexus_SG" {}
variable "port_mysql" {}
variable "RT_cidr_2" {}
variable "tag-MySQL-SG" {}